package com.smartlearning.model;

public class SysKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_key.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_key.key_name
     *
     * @mbggenerated
     */
    private String keyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_key.key_value
     *
     * @mbggenerated
     */
    private String keyValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_key.can_modify
     *
     * @mbggenerated
     */
    private Integer canModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_key.id
     *
     * @return the value of sys_key.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_key.id
     *
     * @param id the value for sys_key.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_key.key_name
     *
     * @return the value of sys_key.key_name
     *
     * @mbggenerated
     */
    public String getKeyName() {
        return keyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_key.key_name
     *
     * @param keyName the value for sys_key.key_name
     *
     * @mbggenerated
     */
    public void setKeyName(String keyName) {
        this.keyName = keyName == null ? null : keyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_key.key_value
     *
     * @return the value of sys_key.key_value
     *
     * @mbggenerated
     */
    public String getKeyValue() {
        return keyValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_key.key_value
     *
     * @param keyValue the value for sys_key.key_value
     *
     * @mbggenerated
     */
    public void setKeyValue(String keyValue) {
        this.keyValue = keyValue == null ? null : keyValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_key.can_modify
     *
     * @return the value of sys_key.can_modify
     *
     * @mbggenerated
     */
    public Integer getCanModify() {
        return canModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_key.can_modify
     *
     * @param canModify the value for sys_key.can_modify
     *
     * @mbggenerated
     */
    public void setCanModify(Integer canModify) {
        this.canModify = canModify;
    }
}