package com.smartlearning.model;

import java.util.Date;

public class SysMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.id
     *
     * @mbggenerated
     */
    private String id;
    
    private int _id; // 通知的id

    public int get_id() {
		return _id;
	}

	public void set_id(int _id) {
		this._id = _id;
	}
	
	private String creatorName;

	public String getCreatorName() {
		return creatorName;
	}

	public void setCreatorName(String creatorName) {
		this.creatorName = creatorName;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.creator
     *
     * @mbggenerated
     */
    private Long creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.organ_name
     *
     * @mbggenerated
     */
    private String organName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.organ_grade
     *
     * @mbggenerated
     */
    private String organGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.organ_degree
     *
     * @mbggenerated
     */
    private Integer organDegree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.sent_time
     *
     * @mbggenerated
     */
    private Date sentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.content
     *
     * @mbggenerated
     */
    private String content;
    
	private String time;// 通知的时间
	
	private int isRead;// 未读已读的标志，0未读，1已读
	
	private int class_id;
	
    public int getClass_id() {
		return class_id;
	}

	public void setClass_id(int class_id) {
		this.class_id = class_id;
	}

	public String getTime() {
		return time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public int getIsRead() {
		return isRead;
	}

	public void setIsRead(int isRead) {
		this.isRead = isRead;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_message.id
     *
     * @return the value of sys_message.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_message.id
     *
     * @param id the value for sys_message.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_message.name
     *
     * @return the value of sys_message.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_message.name
     *
     * @param name the value for sys_message.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_message.status
     *
     * @return the value of sys_message.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_message.status
     *
     * @param status the value for sys_message.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_message.created_time
     *
     * @return the value of sys_message.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_message.created_time
     *
     * @param createdTime the value for sys_message.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_message.creator
     *
     * @return the value of sys_message.creator
     *
     * @mbggenerated
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_message.creator
     *
     * @param creator the value for sys_message.creator
     *
     * @mbggenerated
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_message.organ_name
     *
     * @return the value of sys_message.organ_name
     *
     * @mbggenerated
     */
    public String getOrganName() {
        return organName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_message.organ_name
     *
     * @param organName the value for sys_message.organ_name
     *
     * @mbggenerated
     */
    public void setOrganName(String organName) {
        this.organName = organName == null ? null : organName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_message.organ_grade
     *
     * @return the value of sys_message.organ_grade
     *
     * @mbggenerated
     */
    public String getOrganGrade() {
        return organGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_message.organ_grade
     *
     * @param organGrade the value for sys_message.organ_grade
     *
     * @mbggenerated
     */
    public void setOrganGrade(String organGrade) {
        this.organGrade = organGrade == null ? null : organGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_message.organ_degree
     *
     * @return the value of sys_message.organ_degree
     *
     * @mbggenerated
     */
    public Integer getOrganDegree() {
        return organDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_message.organ_degree
     *
     * @param organDegree the value for sys_message.organ_degree
     *
     * @mbggenerated
     */
    public void setOrganDegree(Integer organDegree) {
        this.organDegree = organDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_message.sent_time
     *
     * @return the value of sys_message.sent_time
     *
     * @mbggenerated
     */
    public Date getSentTime() {
        return sentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_message.sent_time
     *
     * @param sentTime the value for sys_message.sent_time
     *
     * @mbggenerated
     */
    public void setSentTime(Date sentTime) {
        this.sentTime = sentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_message.content
     *
     * @return the value of sys_message.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_message.content
     *
     * @param content the value for sys_message.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
    
}